name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true
      environment:
        description: 'The environment to deploy to'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          npm install
          npm run build --branch ${{ github.event.inputs.branch }}
      - name: Deploy Project
        uses: my-deploy-action@v1
        with:
          environment: ${{ github.event.inputs.environment }}
